version: '3.8'
services:
  mobilenet_v2_small:
    build: .
    container_name: mobilenet_v2_small_app
    command: python src/mobilenet_v2_small/main.py
    volumes:
      - ./src:/app/src
    environment:
      - IMAGE_PATH=/app/src/mobilenet_v2_small/test.png
      - CUDA_VISIBLE_DEVICES=""
    ports:
      - "8000:8000"
